[supervisord]
nodaemon=true

[program:gunicorn]
command=/path/to/venv/bin/gunicorn app.run:server --bind 0.0.0.0:8050
directory=/app
autostart=true
autorestart=true

[program:celery-worker]
command=/path/to/venv/bin/celery -A your_project_name.celery_app worker --loglevel=info -n worker1@%h
directory=/app
autostart=true
autorestart=true

[program:celery-beat]
command=/path/to/venv/bin/celery -A your_project_name.celery_app beat --loglevel=info
directory=/app
autostart=true
autorestart=true