"""Run a demo churn training using the synthetic CSVs generated by generate_synthetic_churn_demo.py

Usage:
    python3 scripts/generate_synthetic_churn_demo.py
    python3 scripts/run_demo_training.py

This will load the demo CSVs into memory (bypassing DB), enqueue the training job, and print job id.
"""
import pandas as pd
import time
from services import training
from app.utils.analytics_helpers import run_churn_training_job

# Load demo files if present
try:
    sales_df = pd.read_csv('sales_demo.csv', parse_dates=['timestamp','date'])
    customers_df = pd.read_csv('customers_demo.csv', parse_dates=['joindate'])
    from etl.transforms import DATA
    DATA['sales'] = sales_df
    DATA['customers'] = customers_df
    print('Loaded demo data into DATA')
except Exception as e:
    print('Failed to load demo data:', e)

jid = training.enqueue_training(run_churn_training_job)
print('Enqueued demo training job:', jid)
# Poll status file
import os, json
path = f'model_store/{jid}_status.json'
for _ in range(60):
    if os.path.exists(path) and os.path.getsize(path) > 0:
        print(open(path).read())
        break
    time.sleep(1)
else:
    print('Status file not available yet:', path)
